# Generated by Django 4.2.11 on 2024-03-06 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms_task", "0005_post"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name="post",
            old_name="category",
            new_name="post_category",
        ),
    ]
