# Generated by Django 4.2.11 on 2024-03-12 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms_task", "0006_postcategory_rename_category_post_post_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="slug",
            field=models.SlugField(default=22),
            preserve_default=False,
        ),
    ]
